apiVersion: v1
kind: Service
metadata:
  name: serving-frontend-internal
  namespace: swiss-ai
spec:
  ports:
  - name: serving-http
    port: 80
    protocol: TCP
    targetPort: 4321
  selector:
    app: serving-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-frontend
  minReadySeconds: 25
  template:
    metadata:
      labels:
        app: serving-frontend
    spec:
      containers:
      - name: serving-frontend
        image: ghcr.io/xiaozheyao/serving-front:dev
        imagePullPolicy: Always
        ports:
          - containerPort: 4321
        envFrom:
          - configMapRef:
              name: serving
          - secretRef:
              name: serving-secrets
      restartPolicy: Always